### ISSUE TITLE
Keyword to execute a dependency if not executed earlier

### ISSUE THREAD

**Issue by aliasgerkw** [mentalisttraceur/robotframework-dependencylibrary#3] opened 2019-12-27 12:53 UTC
Currently "Depends on test" keyword checks the status of the test mentioned and on the basis of that decides the status of caller test.
Suggestion is to create a keyword "Depends on test and execute it" - which will first check if the keyword is executed or not and executes if not. 

`*** Test cases ***`
`This Test Depends on "Passing Test" and executes if not`
    `Depends on test and execute it  Passing Test`
    `Log  The rest of the keywords in this test will run as normal.`

This will help in test level split and if there is test which depends on other for test data will get execute and provide test data to caller test.
Would to contribute for this if Author is open.
Let me know if something is not clear.

**Comment by aliasgerkw** [comment] 2020-01-13 12:55
@mentalisttraceur Are you active on Github, can you please check this request of mine?

**Comment by mentalisttraceur** [comment] 2020-01-14 00:29
@aliasgerkw Yes, I've been thinking about this idea ever since you proposed it.

My initial reaction was "good idea! let's do that!", but then after further thought I got mixed feelings about if this *should* be done, and I've been stuck on trying to figure out how I want to explain my thinking about it.

In the meantime, I'm also not sure how it *could* be done - it looks like Robot Framework only allows programmatically calling *keywords*, not other test cases. Do you have any concrete ideas?

**Comment by aliasgerkw** [comment] 2020-01-14 06:44
@mentalisttraceur As we can execute test using tags we can allow user to pass an unique tag to the keyword. As you are already checking the status of the test case and in case its not executed call 
> robot --include <tag_name> and execute it.
I will do some more research on this and get back to you.

**Comment by mentalisttraceur** [comment] 2020-01-14 15:05
That's a creative way to do it, and it could work for some usecases. Doesn't it feel like a fragile kludge though? In my experience when something requires working around a tool's limitations like that, there is usually a better way.

For example: why don't we just put all the necessary actions into a *keyword* instead of a test case, and then call that keyword conditionally?

So for example, if right now you want:

```
*** Test cases ***
First Test
    some action
    some other action

Second Test
    Depends on test and execute it  First Test
    yet another action
```

Then you could instead do:

```
*** Keywords ***


 with a combination of run keyword if and depends on test?

Seems like we could

Seems easier, simpler, and cleaner than trying to hack around Robot Framework's limitations.

**Comment by mentalisttraceur** [comment] 2020-01-14 15:28
That's a creative way to do it, and it could work for some usecases. Doesn't it feel like a fragile kludge though? In my experience when something requires working around a tool's limitations like that, there is usually a better way.

For example: why can't we just put all the necessary actions into a *keyword* instead of a test case, and then call that keyword conditionally?

So for example, if right now you want:

```robot
*** Test cases ***
First Test
    some action
    some other action

Second Test
    Depends on test and execute it  First Test
    yet another action
```

Then you could instead do:

```robot
*** Keywords ***
Common Actions
    some action
    some other action

*** Test Cases ***
First Test
    Common Actions

Second Test
    ${status}  ${result}= Depends on test  First Test
    Run keyword if  ${status} != PASS  Common Actions
```

To me this seems easier, simpler, and cleaner than trying to work around Robot Framework's limitations.

Would that work in your situation?

**Comment by mentalisttraceur** [comment] 2020-01-14 16:51
Also, I think it's important to ask if the problem you were trying to solve when you thought "I wish I could run this test if it hasn't already ran" could be better solved with an *idempotent* keyword?

In my own work, I try to always solve this kind of problem (one test depending on the system being in a state caused by another test) by

1. putting all the steps needed to get to that state into a separate keyword, and
2. if necessary, making that keyword first *check* if it's already in the right state.

A quick-and-dirty way to do the second part is by just having an "already executed" variable that starts false, and having the keyword set it to true.

A more ideal way is to have it actually check the system being tested somehow, but that's unfortunately not always possible.

Either way, my tests end up looking something like this:

```robot
*** Test cases ***
Test Log In
    Ensure logged out
    Log in

Test Log Out
    Ensure logged in
    Log out

Test Main Menu First Button
    Ensure logged in
    Ensure main menu is open
    # actions to test first button

Test Main Menu Second Button
    Ensure logged in
    Ensure main menu is open
    # actions to test second button

# other tests

*** Keywords ***
Log In
    Navigate to login page
    Enter username
    Enter password
    Click login button
    Wait for page to load
    Find UI element that indicates logged-in state

Ensure Logged In
    ${status} =  Find UI element that incidates logged-in state
    Run keyword if  "${status}" != "PASS"
    ...  Log in

Log Out
    Open user drop-down menu
    Click logout button

Ensure logged out
    ${status} =  Find UI element that indicates logged-in state
    Run keyword if  "${status}" == "PASS"
    ...  Log out

# other keywords
```

(The above might not be exactly correct Robot Framework syntax, and I am omitting best-practices like passing username and password through as arguments, etc. The focus is on the convenient structure and clarity that idempotent keywords bring to tests.)

You could probably tell pretty easily just from the tests a basic gist of how the login and logout functionality works, and *what state each test expects the app to be in*.

And if someone ever deletes or rearranges somes tests, or someone on your team changes a test so that the app is no longer in the same state when Robot Framework gets to your test, it just works.

That seems to be what you're looking for: to ensure that your test gets the system in a certain way, even if other earlier tests didn't run.

I think the key insight here is this:

When there are dependencies between test *behaviors*, Robot Framework already provides *keywords* as the intended means of abstracting that out.

I wrote DependencyLibrary because Robot Framework resists letting people create dependencies between tests, yes, but Robot Framework does so *for good reasons*.

I only reach for it when I absolutely can't find a good way to move behavior that needs to be depended on out of tests and into keywords - when the *least-bad* choice is to fail the test.

But if we have some actions we can execute to make the state of the system correct for our test case, then we don't *really* have a dependency on some other *test case* - we have a dependency on *actions*.

And we can move actions from test cases into their own keywords, at which point instead of depending on the test case, we can make the keyword idempotent, so that the keyword is responsible for making sure it doesn't redo anything if it shouldn't.

Depending on another test is much better than just assuming, but *ensuring* is even better than depending.

**Comment by mentalisttraceur** [comment] 2020-01-31 09:27
I am going to close this for now because I think all the same goals can be achieved by moving the contents of the test case that we want to execute into a keyword and then executing that keyword instead.

I have thought a lot about how else I could help this use-case, but I think the best ways to do that fall outside the scope of this library.

For example, I would probably start by making a "OnceLibrary" which would provide a keyword which takes another keyword as an argument and invokes it only if it hasn't already invoked it.

That is not as good as true idempotent state-ensuring keywords, but should cover most cases which have some behavior they want to always execute either in one test or in another test if the first test didn't execute.

But I am still open to hearing any other ideas on how and why I should implement this, and happy to discuss concrete implementation ideas more.

I could still be convinced to re-open this if someone provides an example where the above suggestions really cannot cover the root need.

**Closed as completed by mentalisttraceur** 2020-01-31 09:27 UTC

**Comment by aliasgerkw** [comment] 2020-02-02 16:02
Thanks @mentalisttraceur 
Yes I think keyword approach will solve my purpose for now.
